### ISSUE TITLE
withStandardLibrary does not import standard library to env

### ISSUE THREAD

**Issue by majecty** [kseo/scheme#59]
withStandardLibrary에서 standard 함수를 읽어오지만 읽어온 Env를 사용하지 않습니다.

지금 withStandardLibarry의 타입이 `withStandardLibrary :: (MonadIO m) => Env -> m () -> m ()` 인데
`withStandardLibrary :: (MonadIO m) => Env -> (Env -> m ()) -> m ()` 가 맞다고 생각합니다.

**Comment by kseo** [comment]
`Env` is an type alias for `IORef [(String, IORef LispVal)]`. So `withStandardLibrary` changes the underlying bindings by evaluating stdlib.scm without creating a new `Env`.

I agree that the current type signature of `withStandardLibrary` is a bit confusing because passing `m ()` is unnecessary. Why don't we change the function name to `loadStandardLibrary` and removes `m ()` argument?

```haskell
loadStandardLibrary :: (MonadIO m) => Env -> m ()
```

**Comment by kseo** [comment]
I renamed `withStandardLibrary` to `loadStandardLibrary` in aff1e4a00edd94d43c6aabb8cd4b0a113ed6cfd5.

**Comment by majecty** [comment]
타입을 읽었을 때 더 이해하기 좋아졌네요.
감사합니다.
